import Head from 'next/head'
import { global } from 'styled-jsx/css';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin , AiFillGithub} from 'react-icons/ai';
import Image  from 'next/image';
import wdev from '../public/wavatar.png';
import design from '../public/design.png';
import code from '../public/code.png';
import project4 from '../public/project4.png';
import project1 from '../public/project1.png';
import project2 from '../public/project2.png';
import project3 from '../public/project3.png';
import {useState} from 'react';




export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ""}>
     <style jsx>{`
      @font-face {
        font-family: "UKIJ Tuz Tom";
          src: url('/public/UKIJTuT.ttf')
      }
      h1, h2, h3, h4, p, span {
        font-family: "UKIJ Tuz Tom";
      }
     
     `}</style>

      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12  flex  justify-between'>
            <h1 className='text-xl font-normal font-extrabold text-transparent  bg-clip-text bg-gradient-to-r from-cyan-500 to-blue-800'>NextJS مەشىق بېتى</h1>
            <ul className='flex items-center'>
             
              <li> 
                <a className=' bg-gradient-to-r from-cyan-600 to-white-600 text-white px-6 py-2 roubg-gradient-to-r from-green-400 to-blue-500 hover:from-cyan-500 hover:to-yellow-500 rounded-md ml-8' href="#">NextJS</a>  
                </li>

                <li className='animate-pulse flex items-center  dark:bg-white '> 
              <BsFillMoonStarsFill  onClick={() => setDarkMode(!darkMode)} 
              className='cursor-pointer text-2xl' /> 
              </li>

            </ul>
          </nav> 
           <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-green-600 font-medium md:text-6xl'>سالام دوسىتلار</h2>
            <h3 className='ext-2xl py-2 text-gray-400 md:text-3xl  '>بۇ بەت NextJS دا يېزىلدى</h3>
            <p className='text-md py-5 leading-8 text-gray-700 md:text-xl'>ھەپتىدە بىر تور بەت ياسىلىپ GitHub غا يوللىنىدۇ</p>
           </div>
            {/*  Social Media  */}
    
           <div className='text-4xl flex justify-center gap-16 py-3 text-cyan-400'> 
           
           <a href='https://twitter.com/warisruzi'>
            <AiFillTwitterCircle />
          </a>
            
            <a href="https://www.linkedin.com/in/waris-ruzi-2ab63090/">
            <AiFillLinkedin />
            </a>
           
           <a href="https://github.com/WarisWorks">
            <AiFillGithub />
            </a>

           </div>
           <div className='relative mx-auto bg-gradient-to-b from-cyan-400 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={wdev}  layout="fill" objectFit='cover' />
           </div>
        </section>
        {/* keyinki bet */}
         <section>
          <div>
            <h3 className='text-3xl py-1 text-cyan-500'>تەجرىبىلىرىم</h3>
            <p className='text-md py-2 leading-8 text-cyan-400'>
              كۆچمە سۇپىغا ئەپ ياساش ۋە ئارقا بەت باشقۇرۇش سېستىمىسى
              React , PhP , Python دا ھەر خىل تور بەتلەرنى ياساش تەجرىبەم بار.
            </p>

            <br />

            <span className='text-2xl text-teal-500'> ئەسەرلىرىم</span>
            <p className='text-md py-2 leading-8 text-gray-80'>
              ئەسەرلىرىمنى كۆرمەكچى بولسىڭىز <span className='text-teal-500'> <a href="https://www.behance.net/warisruzi" target="blank">Behance</a> ياكى GitHub</span> .ئۇلىنىش ئارقىلىق كۆرسىڭىز بولىدۇ
            </p>

            
            <br />
            <p className='text-md leading-8 text-pink-500'>
              كۆرۈنمە يۈز لايىھە <span className='text-teal-500'> UI/UX </span>.<a href='https://www.behance.net/gallery/137815009/Elipbe' target="blank">ۋە كىتاپ بەت لايىھە ئەسەرلىرىم</a>  نەشىردىن چىققان    ۋە ھەقىقىي ئەپتە قوللىنىلىغان
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={design} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>لايىھەلىرىم</h3>
              <p className='py-2'>
                تور بەت كۆرۈنمە يۈزى، ئەپ كۆرۈنمە يۈز ۋە مەھسۇلات چۈشەندۈرۈشى
              </p>
              <h4 className='py-4 text-teal-500'>لايىھەگە ئىشلىتدىغان قوراللىرىم</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className=''>Adobe XD</p>
              <p className=''>Figma</p>
              <p className=''>Adobe Illustrator</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={code} width={70} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>پروگرامما تىلى</h3>
              <p className='py-2'>
               تۆۋەندىكى تىللار بويىچە تۈر ئاچقان ۋە قاتناشقان. 
              </p>
              <h4 className='py-4 text-teal-500'>  </h4>
              <p className='text-gray-800 py-1'>SwiftUI</p>
              <p className=''> Python/Django </p>
              <p className=''>HTML/CSS</p>
              <p className=''> React/NextJS </p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={project4} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>لايىھەلەر</h3>
              <p className='py-2'>
                لايىھەلىرىمنى ياقتۇرغان بولسىڭىز 👍بەلگىسى بېرىشنى ئۇنۇتماڭ
              </p>
              <h4 className='py-4 text-teal-500'>لايىھەگە ئىشلىتدىغان قوراللىرىم</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className=''>Adobe XD</p>
              <p className=''>Figma</p>
              <p className=''>Adobe Illustrator</p>
            </div>
            
          </div>
         </section>

         {/* real projects */}
         <section>
          <div>
            <h3 className='text-3xl py-1 text-cyan-600'>ئەسەرلىرىم</h3>
            <p className='text-md py-2 leading-8 text-gray-80'>
              ئەسەرلىرىمنى كۆرمەكچى بولسىڭىز <span className='text-teal-500'>Behance ياكى GitHub</span> .ئۇلىنىش ئارقىلىق كۆرسىڭىز بولىدۇ
            </p>
          </div>

          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>

            <div className='basis-1/3 flex-1'>
              <Image src={project1} 
              className="rounded-lg object-cover" width={'100%'} 
              height={'70%'} layout="responsive" />
              </div>

            <div className='basis-1/3 flex-1'>
              <Image src={
                project2
              } className="rounded-lg object-cover" width={'100%'}
               height={'70%'} layout="responsive" />
               </div>

            <div className='basis-1/3 flex-1'>
              <Image src={
                project3
              }className="rounded-lg object-cover"width={'100%'} 
              height={'70%'} layout="responsive"/>
            </div>

            <div  className='basis-1/3 flex-1'>
              <Image src={
                project4
              } className="rounded-lg object-cover" width={'100%'} 
                height={'70%'} layout="responsive"/></div>

            <div className='basis-1/3 flex-1'>
              <Image src={
               project4
              }className="rounded-lg object-cover" width={'100%'}
               height={'70%'} layout="responsive"/></div>

            <div className='basis-1/3 flex-1'>
              <Image src={
                project1
              } className="rounded-lg object-cover" width={'100%'} 
             height={'70%'} layout="responsive"/></div>

         </div>
         </section>
      </main>
    </div>
  );
}


{/*  https://nextjs.org/docs/deployment */}